#
# Configuration
#

sudo: required
dist: trusty

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

branches:
  only:
    - master

before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic angular-cli
  - ionic state clear

install: npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng test --watch=false                # unit tests

after_failure:
  - cat $TRAVIS_BUILD_DIR/python_serve.log
  - cat $TRAVIS_BUILD_DIR/ionic_serve.log

after_success:
  # Send coverage info off to cloud ppl
  - bash <(curl -s https://codecov.io/bash)
